fix: serialization sequence fix
shardeum/shardus-core pull request #147
Opened 2024-06-24 19:59 UTC by kgmyatthu

URGENT CRITICAL: This commit fixes the incorrect optional field serialization sequence

2024-06-26 01:57 UTC, afostr requested changes
It looks like things were working before, but this change will cause a failure.   This is because 0 is used on the read side to represent data it seems "=== 0" .

This fix could be changes in both places, and that would be ok.  (this can remain part of the larger set of group changes.  will not need and emergency fix on it.

2024-06-28 03:38 UTC, arhamj commented
I don't think this is true can you recheck the de-serialiser?

2024-07-08 18:34 UTC, kgmyatthu commented
Has this got into the dev?

2024-07-10 06:05 UTC, arhamj commented
This is merged

2024-07-10 06:05 UTC, closed without merging