GOLD-171 : Confirm ntp offset timestamp is within expected range
shardeum/shardus-core pull request #178
Opened 2024-07-09 11:45 UTC by abdulazeem-tk4vr

Linear Task : https://linear.app/shm/issue/GOLD-171/confirm-ntp-offset-timestamp-is-within-expected-range-not-massively

2024-07-10 11:19 UTC, kgmyatthu requested changes

2024-07-10 11:19 UTC, kgmyatthu commented on src/state-manager/index.ts
> +    // Context.network.registerExternalGet('debug-ntp-bad-offset', isDebugModeMiddleware, (_req, res) => {
Need revision on why this code is commented out.

2024-07-10 11:26 UTC, kgmyatthu approved these changes, later dismissed
LGTM

2024-07-15 08:29 UTC, arhamj submitted a review, later dismissed

2024-08-15 06:44 UTC, jintukumardas approved these changes

2024-08-15 06:52 UTC, S0naliThakur approved these changes

2024-08-15 16:04 UTC, merged