BLUE-179 Limiting archivers in the network feature using allowed archivers list
shardeum/shardus-core pull request #305
Opened 2024-09-24 06:47 UTC by jairajdev

- Restrict archivers in the network by adding allowed archivers list in the network config
- Limiting archivers is put behind the allowOnlyApprovedArchivers config
- Added pruneDisallowedArchivers feature to remove active archivers that are not in the new allowed archivers list

2024-09-24 08:16 UTC, thantsintoe submitted a review, later dismissed
The changes are good.

2024-09-24 18:52 UTC, mssabr01 requested changes

2024-09-24 18:52 UTC, mssabr01 commented on src/p2p/Archivers.ts
> +  }
This is checking the sig against the public key in the request, but we've already checked that the pubkey is in the allowed list and is not already in the active archiver list. This is fine

2024-09-24 18:52 UTC, mssabr01 commented on src/p2p/Archivers.ts
> +  if (!crypto.verify(leaveRequest, leaveRequest.nodeInfo.publicKey)) {
Please compare the sig in the leave request to the known public key for the archiver that is requesting to leave. We don't want to verify the sig against an untrusted key that is included in the request. Simply checking that the pub key is present in the active archivers list is not enough, we need to check that the key we know for that archiver is the one that signed the leaveRequest.

2024-09-24 18:52 UTC, mssabr01 commented on src/shardus/shardus-types.ts
> +    pruneDisallowedArchivers: boolean
Is there ever a scenario where we would have allowOnlyApprovedArchivers would be true and pruneDisallowedArchivers would be false? I think pruneDisallowedArchivers is redundant and we want the network to always remove unapproved archivers if allowOnlyApprovedArchivers is true

2024-11-29 17:26 UTC, closed without merging

2024-11-29 17:26 UTC, mssabr01 commented
Stale